site_name: Program Synthesis Benchmarks
# site_url: 

nav:
  - API: api.md

theme:
  name: material
  features:
    - content.code.copy

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg